# see https://github.com/marketplace/actions/release-drafter
# For RESOLVED_VERSION
version-template: '$MAJOR.$MINOR.$PATCH'
#
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
#
template: |
  ### ActionbarPlus-M6 $RESOLVED_VERSION
  [Release Notes](https://github.com/kapresoft/$REPOSITORY/releases/tag/$RESOLVED_VERSION) | [Full Changelog](https://github.com/kapresoft/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)
  
  #### What’s Changed

  $CHANGES
  
  ### Contributors:
  $CONTRIBUTORS
  
  #### Links:

  - [Curse Forge](https://www.curseforge.com/wow/addons/actionbarplus-m6/files) | [Curse Forge Legacy](https://legacy.curseforge.com/wow/addons/actionbarplus-m6/files)
